spring:
  datasource:
    url: jdbc:h2:mem:testdb   # in-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true          # H2 console enable
      path: /h2-console      # access at http://localhost:8080/h2-console
  jpa:
    hibernate:
      ddl-auto: update       # automatically create/update tables
    show-sql: true           # show SQL in console
    properties:
      hibernate:
        format_sql: true
